<script setup lang="ts">
import { ref, onMounted, computed } from "vue";
import TripMap from "../components/TripMap.vue";
import ReplanPanel from "../components/ReplanPanel.vue";
import { useRouter } from "vue-router";

const router = useRouter();

const result = ref<any>(null);
const searchInfo = ref<any>(null);

onMounted(() => {
  const savedResult = localStorage.getItem("trip_result");
  const savedSearch = localStorage.getItem("trip_search");

  try {
    if (savedResult) result.value = JSON.parse(savedResult);
    if (savedSearch) searchInfo.value = JSON.parse(savedSearch);
  } catch {
    localStorage.removeItem("trip_result");
    localStorage.removeItem("trip_search");
  }
});

const dailyPlan = computed(() => result.value?.daily_plan || []);
const places = computed(() => result.value?.places || []);
const weather = computed(() => result.value?.weather || []);

function weatherSource(item: any) {
  switch (item?.source) {
    case "openweather": return "OpenWeather forecast";
    case "openweather_cache": return "OpenWeather forecast (cached)";
    case "demo": return "Demo weather — illustrative values only";
    case "unavailable": return "Weather unavailable";
    default: return "Weather source unverified — generate a new plan";
  }
}

const weatherSources = computed(() => [...new Set(
  dailyPlan.value.map((day: any) => weatherSource(day.weather))
)].join("; ") || "Weather source unverified");

const recommendedPlaces = computed(() => {
  const map = new Map();

  dailyPlan.value.forEach((day: any) => {
    const activities = day.activities || [];

    activities.forEach((activity: any) => {
      if (
        activity?.name &&
        activity?.lat !== null && activity?.lat !== undefined &&
        activity?.lon !== null && activity?.lon !== undefined
      ) {
        map.set(activity.name, activity);
      }
    });
  });

  return Array.from(map.values());
});

function goBack() {
  router.push("/");
}

function formatTags(tags: string[]) {
  if (!tags || !Array.isArray(tags)) return "general";
  return tags.join(", ");
}
</script>

<template>
  <div class="result-page">
    <header class="topbar">
      <div>
        <p class="eyebrow">Generated Itinerary</p>
        <h1>Trip Plan Result</h1>
      </div>

      <button class="back-btn" @click="goBack">
        Back to Search
      </button>
    </header>

    <section v-if="result" class="summary-grid">
      <div class="summary-card main-summary">
        <h2>{{ result.destination }}</h2>
        <p>Suggested itinerary using attraction data and the weather sources shown below.</p>

        <div class="summary-meta">
          <span>{{ result.days }} days</span>
          <span>Budget ${{ result.budget }}</span>
          <span>{{ result.preference }}</span>
        </div>
      </div>

      <div class="summary-card">
        <h3>Origin</h3>
        <p>{{ result.origin }}</p>
      </div>

      <div class="summary-card">
        <h3>Destination</h3>
        <p>{{ result.destination }}</p>
      </div>

      <div class="summary-card">
        <h3>Data Source</h3>
        <p>{{ weatherSources }}</p>
        <p>Attractions: OpenTripMap and curated examples (may be cached).</p>
      </div>
    </section>

    <ReplanPanel v-if="result" :plan="result" :search-info="searchInfo" />

    <section v-if="result" class="section">
      <div class="section-title">
        <h2>Recommended Places Map</h2>
        <p>
          The map shows the recommended attractions generated by the itinerary algorithm.
        </p>
      </div>

      <TripMap :places="recommendedPlaces" />
    </section>

    <section v-if="result" class="section">
      <div class="section-title">
        <h2>Daily Itinerary</h2>
        <p>Recommendations are adjusted based on weather, tags and budget.</p>
      </div>

      <div class="day-list">
        <article v-for="day in dailyPlan" :key="day.day" class="day-card">
          <div class="day-header">
            <span class="day-badge">Day {{ day.day }}</span>
            <h3>{{ day.date }}</h3>
          </div>

          <div class="weather-box">
            <p><strong>{{ weatherSource(day.weather) }}</strong></p>
            <p><strong>Weather:</strong> {{ day.weather?.weather }}</p>
            <p><strong>Temperature:</strong> {{ day.weather?.temp == null ? 'Unavailable' : `${day.weather.temp}°C` }}</p>
            <p><strong>Rain probability:</strong> {{ day.weather?.rain_probability == null ? 'Unavailable' : `${day.weather.rain_probability}%` }}</p>
          </div>

          <div class="advice-box">
            <strong>Advice</strong>
            <p>{{ day.advice }}</p>
          </div>

          <div class="activity-list">
            <h4>Recommended Activities</h4>

            <div
              v-for="activity in day.activities"
              :key="activity.name"
              class="activity-card"
            >
              <div>
                <h5>{{ activity.name }}</h5>
                <p>{{ formatTags(activity.tags) }}</p>
              </div>

              <span>${{ activity.estimated_cost }}</span>
            </div>
          </div>
        </article>
      </div>
    </section>

    <section v-if="result" class="section">
      <div class="section-title">
        <h2>Weather Forecast</h2>
        <p>Weather data used by the itinerary recommendation logic.</p>
      </div>

      <div class="weather-grid">
        <div v-for="item in weather" :key="item.date" class="weather-card">
          <h3>{{ item.date }}</h3>
          <p><strong>{{ weatherSource(item) }}</strong></p>
          <p class="temp">{{ item.temp }}°C</p>
          <p>{{ item.weather }}</p>
          <p>Rain: {{ item.rain_probability }}%</p>
        </div>
      </div>
    </section>

    <section v-if="result" class="section">
      <div class="section-title">
        <h2>All Retrieved Places</h2>
        <p>Attraction API results supplemented with curated examples; costs and durations are estimates.</p>
      </div>

      <div class="places-grid">
        <div v-for="place in places" :key="place.name" class="place-card">
          <h3>{{ place.name }}</h3>
          <p class="tags">{{ formatTags(place.tags) }}</p>
          <p class="small">Estimated cost: ${{ place.estimated_cost }}</p>
          <p class="small">Duration: {{ place.duration }} hours</p>
        </div>
      </div>
    </section>

    <section v-else class="empty-state">
      <h1>No trip result found</h1>
      <p>Please go back to the homepage and generate a trip plan first.</p>
      <button class="back-btn" @click="goBack">Back to Search</button>
    </section>
  </div>
</template>

<style scoped>
.result-page {
  min-height: 100vh;
  padding: 32px;
  background: #f8fafc;
  color: #0f172a;
  font-family: Arial, Helvetica, sans-serif;
}

.topbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 28px;
}

.eyebrow {
  color: #14735f;
  font-weight: 800;
  margin-bottom: 6px;
}

.topbar h1 {
  font-size: 36px;
  margin: 0;
}

.back-btn {
  padding: 12px 18px;
  border: none;
  border-radius: 12px;
  background: #14735f;
  color: white;
  font-weight: 800;
  cursor: pointer;
}

.summary-grid {
  display: grid;
  grid-template-columns: 2fr 1fr 1fr 1fr;
  gap: 16px;
  margin-bottom: 32px;
}

.summary-card {
  background: white;
  padding: 22px;
  border-radius: 20px;
  box-shadow: 0 10px 28px rgba(15, 23, 42, 0.07);
}

.main-summary {
  background: linear-gradient(135deg, #14735f, #1e8a75);
  color: white;
}

.main-summary p {
  color: rgba(255, 255, 255, 0.84);
}

.summary-card h2,
.summary-card h3 {
  margin: 0 0 10px;
}

.summary-card p {
  margin: 0;
  color: #64748b;
}

.main-summary p {
  color: rgba(255, 255, 255, 0.86);
}

.summary-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 18px;
}

.summary-meta span {
  background: rgba(255, 255, 255, 0.18);
  padding: 8px 12px;
  border-radius: 999px;
  font-size: 14px;
  font-weight: 700;
}

.section {
  margin-bottom: 34px;
}

.section-title {
  margin-bottom: 16px;
}

.section-title h2 {
  font-size: 28px;
  margin: 0 0 6px;
}

.section-title p {
  color: #64748b;
  margin: 0;
}

.day-list {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
}

.day-card {
  background: white;
  border-radius: 22px;
  padding: 22px;
  box-shadow: 0 10px 28px rgba(15, 23, 42, 0.07);
}

.day-header {
  margin-bottom: 16px;
}

.day-badge {
  display: inline-block;
  background: #e0f2ef;
  color: #14735f;
  padding: 7px 12px;
  border-radius: 999px;
  font-weight: 800;
  margin-bottom: 12px;
}

.day-header h3 {
  margin: 0;
  font-size: 22px;
}

.weather-box,
.advice-box {
  background: #f8fafc;
  padding: 14px;
  border-radius: 14px;
  margin-bottom: 14px;
}

.weather-box p,
.advice-box p {
  margin: 6px 0;
  color: #475569;
}

.activity-list h4 {
  margin: 10px 0 12px;
}

.activity-card {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  padding: 12px;
  border: 1px solid #e2e8f0;
  border-radius: 14px;
  margin-bottom: 10px;
}

.activity-card h5 {
  margin: 0 0 6px;
  font-size: 15px;
}

.activity-card p {
  margin: 0;
  color: #64748b;
  font-size: 13px;
}

.activity-card span {
  font-weight: 800;
  color: #14735f;
}

.weather-grid,
.places-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
}

.weather-card,
.place-card {
  background: white;
  padding: 20px;
  border-radius: 18px;
  box-shadow: 0 8px 22px rgba(15, 23, 42, 0.06);
}

.weather-card h3,
.place-card h3 {
  margin: 0 0 10px;
}

.temp {
  font-size: 28px;
  font-weight: 800;
  color: #14735f;
}

.tags {
  color: #14735f;
  font-weight: 700;
}

.small {
  color: #64748b;
  font-size: 14px;
}

.empty-state {
  height: 70vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

@media (max-width: 1100px) {
  .summary-grid,
  .day-list,
  .weather-grid,
  .places-grid {
    grid-template-columns: 1fr;
  }

  .topbar {
    align-items: flex-start;
    flex-direction: column;
    gap: 16px;
  }
}
</style>
